### PR TITLE
Fix missing empty .psm1 file

### PR DESCRIPTION
**Pull request by johlju**
### Fixed

-  An empty .psm1 file is required if the module manifest contain the
   property `RootModule`. If this does not exist it is not possible to
   run the build task (fails with invalid module manifest).

---
This change is [Reviewable](https://reviewable.io/reviews/raandree/datum.invokecommand/1)

### CODE REVIEW

**Comment by johlju** [comment]
I pushing commits to this PR but they does not show up here. GitHub are having issues.

**Comment by raandree** [comment]
Thank you very much for your quick help!

**Comment by johlju** [comment]
I just pushed a new commit second before you merged. 😄 I removed (I hope) the tests that was making the build fail. Will see when the build completes.

**Comment by johlju** [comment]
...and no problem! Was interested if there was something breaking in new release or something. 😄

**Comment by johlju** [comment]
The HQRM test was not skipped. 

```
 Describing Common Tests - Script Resource Schema Validation
    [-] Error occurred in Describe block 0ms
      FileNotFoundException: The specified module 'xDscResourceDesigner' was not loaded because no valid module file was found in any module directory.
      at <ScriptBlock>, D:\a\1\s\output\RequiredModules\DscResource.Test\0.13.3\Tests\QA\ResourceSchema.common.Tests.ps1: line 39
      at DescribeImpl, D:\a\1\s\output\RequiredModules\Pester\4.10.1\Functions\Describe.ps1: line 213
```

**Comment by johlju** [comment]
https://github.com/raandree/Datum.InvokeCommand/blob/7c66a8b66de5e3c57104cd5a761a05c42e88bdc9/build.yaml#L64

I think you can change that to `'WindowsOnly`. That will skip the the tests:
https://github.com/dsccommunity/DscResource.Test/search?q=%27WindowsOnly%27&unscoped_q=%27WindowsOnly%27

**Comment by raandree** [comment]
Does adding 'xDscResourceDesigner' to the required modules solves that as well? I would like to get this tested on PowerShell 7 as well.

**Comment by johlju** [comment]
Yes it will solve it. I though you intentionally removed that module since you didn't expected to have DSC resources. :)

Easiest is adding  'xDscResourceDesigner' to RequiredModules.psd1 and removing `'Common Tests - Script Resource Schema Validation'`  from the build.yaml that I added just second sbefore you merged. 😄

**Comment by raandree** [comment]
Will do this then. Even if this will not contain any DSC resource having the check does not hurt.

I have only one issues building locally with PowerShell 7

```
    [-] Changelog has been updated 208ms
      Expected a value, because the changelog should have at least one entry for every pull request, but got $null or empty.
      49:                 } | Should -Not -BeNullOrEmpty -Because 'the changelog should have at least one entry for every pull request'
      at <ScriptBlock>, C:\Git\Datum.InvokeCommand\output\RequiredModules\DscResource.Test\0.13.3\Tests\QA\Changelog.common.Tests.ps1: line 47
```

But you have added a change to the change log?!?

And interestingly I still have this one but only building with Windows PowerShell. I don't see it when building with PowerShell 7:

```
    Context Datum.InvokeCommand.psm1
WARNING: Datum.InvokeCommand.psm1 contain Byte Order Mark (BOM). Use fixer function 'ConvertTo-ASCII'.
      [-] Module file 'Datum.InvokeCommand.psm1' should not have Byte Order Mark (BOM) 11ms
        Expected $false, but got $true.
        39:                 $moduleFileHasBom | Should -BeFalse
        at <ScriptBlock>, C:\Git\Datum.InvokeCommand\output\RequiredModules\DscResource.Test\0.13.3\Tests\QA\ModuleFiles.common.Tests.ps1: line 39
```

**Comment by johlju** [comment]
So we have a separate test för HQRM that runs in DSC modules and I have not run those test in PS7, so not sure how it behave or if it is skipped on Liniux and macOS test jobs https://github.com/dsccommunity/SqlServerDsc/blob/a75b66c0ea4ae5878d9507ce3c9180e749cfb684/azure-pipelines.yml#L52-L78

> [-] Changelog has been updated 208ms

It checks that there is a commit for the change log. If you add a change to the change log and commit the error disappears.

> Module file 'Datum.InvokeCommand.psm1' should not have Byte Order Mark (BOM) 11ms

Not seeing that in PS7 on my side. I will clone the repo again to verify.

**Comment by johlju** [comment]
My bad, you saw the last issue in Windows PowerShell... Trying to repro that.

**Pull request merged**
