### PR TITLE
Expose calling .yml file properties to scriptblock

### PR DESCRIPTION
**Pull request by riddlertom**

### CODE REVIEW

**Comment by raandree** [comment]
Can you give an example when this makes sense, please? Specifying the YamlFilePath in the Datum.yml does not give you the context of the current node as this is evaluated only once during the runtime.

When do you want to access 'node.yml/role.yaml/location.yaml/environment.yaml'? The values from the other levels are accessible anyway thank to the Datum merging features.

**Comment by riddlertom** [comment]
I'm calling multiple other subdatum structures that I build dynamically as
part of a master datum.

**Comment by raandree** [comment]
Sorry, I am still not getting the point. If you have multiple datum structures, wouldn't you then use 'New-DatumStructure' instead of   'ConvertFrom-Yaml'?

Can you give us some more context on the how you use datum?

**Comment by riddlertom** [comment]
Setup a call man, I'm working crazy long hours and have already moved

I went through the dev branch of datum debugging a couple things as I went.

I understand what you're saying about the values being available, but even
after I emailed Gael about my scenario this was the only way it could be
done.

**Comment by raandree** [comment]
@riddlertom, I know quite a lot of time has passed? Are you still working on this?

**Comment by riddlertom** [comment]
I haven't been working on it for a while, but I still have the code that I
may ultimately end up utilizing.
I've been tasked with moving this company that I developed that add-on for
to the cloud starting in quarter one of 2022, so this is about to get a lot
of scrutiny I imagine. Sounds like we're going to Amazon AWS, so we may end
up utilizing DS2 for our Thursday configuration as well as their targeting
system (although I'm not totally familiar how it'll work).
I'm guessing it'll be a compare and contrast situation.

**Comment by raandree** [comment]
Closing this for now. Context is missing and date to reproduce whatever this PR was created for.

**Pull request closed without merging**
